<?php
/**
 * RmaApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Rma
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RMA Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Rma\Test\Api;

use \GeminiCommerce\Rma\Configuration;
use \GeminiCommerce\Rma\ApiException;
use \GeminiCommerce\Rma\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RmaApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Rma
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RmaApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addNote
     *
     * Add a note to an RMA.
     *
     */
    public function testAddNote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for approveReturn
     *
     * Approve a return.
     *
     */
    public function testApproveReturn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelReturn
     *
     * Cancel a return.
     *
     */
    public function testCancelReturn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for confirmReturnApproveItems
     *
     * Confirm return approve items.
     *
     */
    public function testConfirmReturnApproveItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createReturn
     *
     * Create a return.
     *
     */
    public function testCreateReturn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteNote
     *
     * Delete a note from an RMA.
     *
     */
    public function testDeleteNote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editNote
     *
     * Edit a note on an RMA.
     *
     */
    public function testEditNote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReturn
     *
     * Get a return.
     *
     */
    public function testGetReturn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listNotesByReturnId
     *
     * List notes by return id.
     *
     */
    public function testListNotesByReturnId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listReturns
     *
     * List returns.
     *
     */
    public function testListReturns()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for refundReturn
     *
     * Refund a return.
     *
     */
    public function testRefundReturn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rejectReturn
     *
     * Reject a return.
     *
     */
    public function testRejectReturn()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setReceivedItems
     *
     * Set received items.
     *
     */
    public function testSetReceivedItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for skipReturnStatus
     *
     * Skip a return status.
     *
     */
    public function testSkipReturnStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
